import { describe, expect, it } from 'vitest';
import type { Project } from './project';
import { autoAssignChannelProtocolOutputIds, removeChannel, renameChannel, reorderChannels, setChannelProtocolOutputId } from './projectOperations';

const at = '2026-01-01T00:00:00.000Z';
const project = (): Project => ({ schemaVersion: 3, id: 'p', name: 'Show', createdAt: at, updatedAt: at, audio: null, score: { version: 1, events: [] }, deviceBindings: [], costumes: [{ id: 'c', name: 'C', master: { id: 'm', displayName: 'M', type: 'esp32', slaves: [{ id: 's1', displayName: 'P1', type: 'raspberry-pi-pico', logicalAddress: 7, channels: [{ id: 'a', displayName: 'A', type: 'el-wire', hardwareOutputIdentifier: 'GP10' }, { id: 'b', displayName: 'B', type: 'el-wire', hardwareOutputIdentifier: 'relay-left' }] }, { id: 's2', displayName: 'P2', type: 'raspberry-pi-pico', logicalAddress: 8, channels: [{ id: 'c2', displayName: 'C', type: 'el-wire', hardwareOutputIdentifier: 'wire-1' }] }] } }] });
const channel = (value: Project, id: string) => value.costumes.flatMap(c => c.master.slaves).flatMap(s => s.channels).find(c => c.id === id)!;

describe('protocol output mapping', () => {
  it('is optional, supports boundaries, set and clear', () => { let value = project(); expect(channel(value, 'a').protocolOutputId).toBeUndefined(); value = setChannelProtocolOutputId(value, 'a', 0, at); expect(channel(value, 'a').protocolOutputId).toBe(0); value = setChannelProtocolOutputId(value, 'a', 255, at); expect(channel(value, 'a').protocolOutputId).toBe(255); value = setChannelProtocolOutputId(value, 'a', undefined, at); expect(channel(value, 'a').protocolOutputId).toBeUndefined(); });
  it.each([-1, 256, 1.5])('rejects invalid ID %s without changing input', id => { const value = project(); expect(() => setChannelProtocolOutputId(value, 'a', id, at)).toThrow(); expect(channel(value, 'a').protocolOutputId).toBeUndefined(); });
  it('rejects duplicates inside one Pico but permits them on different Picos', () => { let value = setChannelProtocolOutputId(project(), 'a', 0, at); expect(() => setChannelProtocolOutputId(value, 'b', 0, at)).toThrow(/unique/); value = setChannelProtocolOutputId(value, 'c2', 0, at); expect(channel(value, 'c2').protocolOutputId).toBe(0); });
  it('survives rename and reorder and disappears with its channel', () => { let value = setChannelProtocolOutputId(project(), 'a', 4, at); value = renameChannel(value, 'a', 'Renamed', at); value = reorderChannels(value, 's1', 0, 1, at); expect(channel(value, 'a')).toMatchObject({ displayName: 'Renamed', protocolOutputId: 4 }); value = removeChannel(value, 'a', at); expect(value.costumes[0].master.slaves[0].channels.some(c => c.id === 'a')).toBe(false); });
  it('auto assigns every channel in topology order without parsing identifiers', () => { const value = autoAssignChannelProtocolOutputIds(project(), 's1', at); expect(value.costumes[0].master.slaves[0].channels.map(c => c.protocolOutputId)).toEqual([0, 1]); });
  it('rejects auto assignment over 256 channels atomically', () => { const value = project(); value.costumes[0].master.slaves[0].channels = Array.from({ length: 257 }, (_, i) => ({ id: `x${i}`, displayName: `X${i}`, type: 'el-wire' as const, hardwareOutputIdentifier: `pin-${i}` })); expect(() => autoAssignChannelProtocolOutputIds(value, 's1', at)).toThrow(/256/); expect(value.costumes[0].master.slaves[0].channels.every(c => c.protocolOutputId === undefined)).toBe(true); });
});
