import { describe, expect, it } from 'vitest';
import type { Project } from '../domain/project';
import { setProjectAudio, removeProjectAudio, AudioDurationConflictError } from '../domain/audioOperations';
import { changeChannelHardwareOutputIdentifier, removeChannel, removeCostume, removeSlave, renameChannel, reorderChannels } from '../domain/projectOperations';
import { validateProject } from '../domain/projectValidation';
import { createLightInterval, moveLightInterval, removeScoreEvent, resizeLightInterval, ScoreOperationError } from './scoreOperations';

const at = '2026-09-25T00:00:00.000Z';
const id = (value: string) => () => value;
const base = (): Project => ({ schemaVersion: 3, id: 'p', name: 'Show', createdAt: at, updatedAt: at, audio: null, costumes: [
  { id: 'costume-a', name: 'A', master: { id: 'master-a', displayName: 'M', type: 'esp32', slaves: [{ id: 'pico-a', displayName: 'P', type: 'raspberry-pi-pico', channels: [{ id: 'a', displayName: 'A', type: 'el-wire', hardwareOutputIdentifier: '0' }, { id: 'b', displayName: 'B', type: 'digital-output', hardwareOutputIdentifier: '1' }, { id: 'led', displayName: 'LED', type: 'addressable-led', hardwareOutputIdentifier: '2' }] }] } },
  { id: 'costume-b', name: 'B', master: { id: 'master-b', displayName: 'M2', type: 'esp32', slaves: [{ id: 'pico-b', displayName: 'P2', type: 'raspberry-pi-pico', channels: [{ id: 'c', displayName: 'C', type: 'el-wire', hardwareOutputIdentifier: '0' }] }] } },
], score: { version: 1, events: [] }, deviceBindings: [] });
const add = (project: Project, eventId: string, channelId = 'a', startMs = 100, endMs = 200) => createLightInterval(project, { channelId, startMs, endMs }, id(eventId), at);

describe('Score v1 operations', () => {
  it('creates and removes an interval with a stable generated ID', () => { const created = add(base(), 'event'); expect(created.score.events[0]).toEqual({ id: 'event', kind: 'light-interval', channelId: 'a', startMs: 100, endMs: 200 }); expect(removeScoreEvent(created, 'event', at).score.events).toEqual([]); });
  it('moves while preserving duration and ID', () => { const moved = moveLightInterval(add(base(), 'event'), 'event', 300, at); expect(moved.score.events[0]).toMatchObject({ id: 'event', startMs: 300, endMs: 400 }); });
  it('resizes either edge while preserving ID', () => { let value = resizeLightInterval(add(base(), 'event'), 'event', { startMs: 50 }, at); expect(value.score.events[0]).toMatchObject({ id: 'event', startMs: 50, endMs: 200 }); value = resizeLightInterval(value, 'event', { endMs: 250 }, at); expect(value.score.events[0]).toMatchObject({ id: 'event', startMs: 50, endMs: 250 }); });
  it.each([[-1, 100], [100, 100], [200, 100], [1.5, 100]])('rejects invalid range %s..%s', (startMs, endMs) => expect(() => add(base(), 'event', 'a', startMs, endMs)).toThrow(ScoreOperationError));
  it('rejects overlap on one channel with structured conflict details', () => { const value = add(base(), 'first', 'a', 100, 300); try { add(value, 'second', 'a', 200, 400); } catch (error) { expect(error).toMatchObject({ code: 'overlap', details: { channelId: 'a', conflictingEventId: 'first', attemptedInterval: { startMs: 200, endMs: 400 } } }); } });
  it('allows adjacent intervals, overlaps on different channels, and simultaneous events across costumes', () => { let value = add(base(), 'one', 'a', 100, 200); value = add(value, 'two', 'a', 200, 300); value = add(value, 'three', 'b', 150, 250); value = add(value, 'four', 'c', 150, 250); expect(value.score.events).toHaveLength(4); });
  it('rejects missing and unsupported output channels', () => { expect(() => add(base(), 'x', 'missing')).toThrowError(expect.objectContaining({ code: 'channel-not-found' })); expect(() => add(base(), 'x', 'led')).toThrowError(expect.objectContaining({ code: 'unsupported-channel-type' })); });
  it('enforces known audio bounds but permits a score without audio', () => { const scored = add(base(), 'event', 'a', 100, 500); const withAudio = setProjectAudio(scored, { displayName: 'music', uri: 'file:///x', durationMs: 500 }, id('audio'), at); expect(withAudio.audio?.durationMs).toBe(500); expect(() => setProjectAudio(scored, { displayName: 'short', uri: 'file:///x', durationMs: 499 }, id('audio'), at)).toThrow(AudioDurationConflictError); expect(() => add({ ...base(), audio: { id: 'audio', displayName: 'x', reference: { type: 'external-uri', uri: 'x' }, durationMs: 150 } }, 'event', 'a', 100, 200)).toThrowError(expect.objectContaining({ code: 'audio-bounds' })); expect(removeProjectAudio(withAudio, at).score).toEqual(scored.score); });
  it('rename, reorder, and hardware binding edits preserve score references and IDs', () => { const scored = add(base(), 'event'); const expected = scored.score; expect(renameChannel(scored, 'a', 'Renamed', at).score).toEqual(expected); expect(reorderChannels(scored, 'pico-a', 0, 2, at).score).toEqual(expected); expect(changeChannelHardwareOutputIdentifier(scored, 'a', 'GP9', at).score).toEqual(expected); });
  it('cascades event deletion for channel, Pico, and Costume deletion', () => { let scored = add(base(), 'a-event', 'a'); scored = add(scored, 'b-event', 'b'); scored = add(scored, 'c-event', 'c'); expect(removeChannel(scored, 'a', at).score.events.map(e => e.id)).toEqual(['b-event', 'c-event']); expect(removeSlave(scored, 'pico-a', at).score.events.map(e => e.id)).toEqual(['c-event']); expect(removeCostume(scored, 'costume-a', at).score.events.map(e => e.id)).toEqual(['c-event']); });
  it('aggregate validation detects score version, duplicate IDs, dangling refs, bad ranges, overlap, and audio bounds', () => { const scored = add(base(), 'event'); const mutations: Project[] = [ { ...scored, score: { ...scored.score, version: 2 as 1 } }, { ...scored, score: { ...scored.score, events: [...scored.score.events, { ...scored.score.events[0] }] } }, { ...scored, score: { ...scored.score, events: [{ ...scored.score.events[0], channelId: 'missing' }] } }, { ...scored, score: { ...scored.score, events: [{ ...scored.score.events[0], endMs: 100 }] } }, { ...scored, score: { ...scored.score, events: [...scored.score.events, { ...scored.score.events[0], id: 'event2', startMs: 150, endMs: 250 }] } }, { ...scored, audio: { id: 'audio', displayName: 'x', reference: { type: 'external-uri', uri: 'x' }, durationMs: 150 } } ]; expect(mutations.every(value => validateProject(value).length > 0)).toBe(true); });
});
