#include "master/prepared_binary.hpp"
#include "master/desktop_protocol.hpp"
#include <array>
#include <utility>
namespace master {
OwnedPreparedMasterShow::OwnedPreparedMasterShow(const OwnedPreparedMasterShow&o):duration_ms(o.duration_ms),frames(o.frames){}OwnedPreparedMasterShow&OwnedPreparedMasterShow::operator=(const OwnedPreparedMasterShow&o){duration_ms=o.duration_ms;frames=o.frames;return *this;}OwnedPreparedMasterShow::OwnedPreparedMasterShow(OwnedPreparedMasterShow&&o)noexcept:duration_ms(o.duration_ms),frames(std::move(o.frames)){}OwnedPreparedMasterShow&OwnedPreparedMasterShow::operator=(OwnedPreparedMasterShow&&o)noexcept{duration_ms=o.duration_ms;frames=std::move(o.frames);return *this;}
void OwnedPreparedMasterShow::rebuild()const{batch_views_.clear();frame_views_.clear();batch_views_.resize(frames.size());for(size_t i=0;i<frames.size();i++){for(auto&b:frames[i].batches)batch_views_[i].push_back({b.address,b.updates.data(),b.updates.size()});frame_views_.push_back({frames[i].time_ms,batch_views_[i].data(),batch_views_[i].size()});}view_={duration_ms,frame_views_.data(),frame_views_.size()};}
const PreparedMasterShow&OwnedPreparedMasterShow::view()const{rebuild();return view_;}
bool decode_prepared_master_binary(const uint8_t*p,size_t n,OwnedPreparedMasterShow&out){using desktop_protocol::read16;using desktop_protocol::read32;if(n<12||p[0]!='P'||p[1]!='M'||p[2]!='B'||p[3]!='1'||p[4]!=1||p[5]!=0)return false;size_t at=6;OwnedPreparedMasterShow x;x.duration_ms=read32(p+at);at+=4;auto count=read16(p+at);at+=2;x.frames.reserve(count);uint32_t prior=0;for(size_t i=0;i<count;i++){if(at+5>n)return false;OwnedPreparedMasterShow::Frame f;f.time_ms=read32(p+at);at+=4;auto bc=p[at++];if(f.time_ms>x.duration_ms||(i&&f.time_ms<=prior))return false;prior=f.time_ms;std::array<bool,255>slaves{};f.batches.reserve(bc);for(size_t b=0;b<bc;b++){if(at+2>n)return false;OwnedPreparedMasterShow::Batch batch;batch.address=p[at++];auto uc=p[at++];if(batch.address==255||slaves[batch.address]||uc==0||uc>31)return false;slaves[batch.address]=true;if(at+size_t(uc)*2>n)return false;std::array<bool,256>outputs{};for(size_t u=0;u<uc;u++){auto id=p[at++],state=p[at++];if(outputs[id]||state>1)return false;outputs[id]=true;batch.updates.push_back({id,state?OutputState::On:OutputState::Off});}f.batches.push_back(std::move(batch));}x.frames.push_back(std::move(f));}if(at!=n||!validate_show(x.view()))return false;out=std::move(x);return true;}
}
