#include "master/session_manager.hpp"
#include <algorithm>
namespace master {
SessionManager::SessionManager(PicoTransport&t,MonotonicClock&c,uint32_t n,SessionEvents*e):transport_(t),clock_(c),nonce_(n?n:1),events_(e){}
SlaveSession* SessionManager::find(uint8_t a){for(auto&s:slaves_)if(s.used&&s.address==a)return &s;return nullptr;} const SlaveSession* SessionManager::find(uint8_t a)const{for(auto&s:slaves_)if(s.used&&s.address==a)return &s;return nullptr;}
bool SessionManager::add_slave(uint8_t a){if(a==255)return false;if(find(a))return true;for(auto&s:slaves_)if(!s.used){s.used=true;s.address=a;s.session_id=nonce_^(0x9e3779b9u*(uint32_t(a)+1));if(!s.session_id)s.session_id=1;return true;}return false;}
bool SessionManager::send_request(SlaveSession&s,protocol::Type type,const uint8_t*p,size_t n,RequestClass cls,const PreparedSlaveBatch*b){if(cls==RequestClass::Realtime||type==protocol::Type::ResetOutputs)for(auto&x:s.pending)if(x.active&&x.request_class==RequestClass::Realtime)x.active=false;PendingRequest*slot=nullptr;for(auto&x:s.pending)if(!x.active){slot=&x;break;}if(!slot)return false;protocol::Frame f{type,s.address,s.next_sequence++,s.session_id};f.payload_size=uint16_t(n);std::copy_n(p,n,f.payload.data());if(!protocol::encode(f,slot->encoded)||!transport_.send(s.address,slot->encoded.data.data(),slot->encoded.size))return false;slot->active=true;slot->sequence=f.sequence;slot->type=type;slot->request_class=cls;slot->sent_us=clock_.now_us();slot->attempts=1;slot->outputs={};if(b)for(size_t i=0;i<b->update_count;i++)slot->outputs[b->updates[i].output_id]=true;return true;}
bool SessionManager::start_hello(uint8_t a){auto*s=find(a);return s&&send_request(*s,protocol::Type::Hello,nullptr,0,RequestClass::Control,nullptr);}
bool SessionManager::send_reset(uint8_t a){auto*s=find(a);return s&&send_request(*s,protocol::Type::ResetOutputs,nullptr,0,RequestClass::Control,nullptr);}
bool SessionManager::send_status(uint8_t a){auto*s=find(a);return s&&send_request(*s,protocol::Type::GetStatus,nullptr,0,RequestClass::Control,nullptr);}
bool SessionManager::send_updates(const PreparedSlaveBatch&b){auto*s=find(b.slave_address);if(!s||!s->online||s->faulted||b.update_count>31)return false;uint8_t p[63];p[0]=uint8_t(b.update_count);for(size_t i=0;i<b.update_count;i++){p[1+2*i]=b.updates[i].output_id;p[2+2*i]=uint8_t(b.updates[i].state);}return send_request(*s,protocol::Type::SetOutputs,p,1+2*b.update_count,RequestClass::Realtime,&b);}
void SessionManager::parsed(void*c,const protocol::Frame&f){static_cast<SessionManager*>(c)->on_frame(f);} void SessionManager::ingest(const uint8_t*p,size_t n){parser_.push(p,n,parsed,this);}
void SessionManager::on_frame(const protocol::Frame&f){auto*s=find(f.address);if(!s||s->session_id!=f.session)return;PendingRequest*p=nullptr;for(auto&x:s->pending)if(x.active&&x.sequence==f.sequence){p=&x;break;}if(!p)return;s->last_response_us=clock_.now_us();if(f.type==protocol::Type::Nack&&f.payload_size==1){s->last_nack=f.payload[0];s->faulted=true;p->active=false;if(events_)events_->fault(s->address,"NACK");return;}bool match=(p->type==protocol::Type::Hello&&f.type==protocol::Type::HelloAck&&f.payload_size==5)||(p->type==protocol::Type::GetStatus&&f.type==protocol::Type::Status)||(p->type==protocol::Type::Ping&&f.type==protocol::Type::Pong)||(f.type==protocol::Type::Ack);if(match){if(p->type==protocol::Type::Hello)s->online=true;p->active=false;if(events_)events_->response(s->address,f.type,f.sequence);}}
void SessionManager::service_timeouts(){auto now=clock_.now_us();for(auto&s:slaves_)if(s.used)for(auto&p:s.pending)if(p.active&&now-p.sent_us>=kTimeoutUs){if(p.attempts<kMaxAttempts&&transport_.send(s.address,p.encoded.data.data(),p.encoded.size)){++p.attempts;p.sent_us=now;if(events_)events_->retry(s.address,p.type,p.sequence,p.attempts);}else{p.active=false;s.faulted=true;s.online=false;if(events_)events_->fault(s.address,"timeout");}}}
bool SessionManager::all_online()const{bool any=false;for(auto&s:slaves_)if(s.used){any=true;if(!s.online||s.faulted)return false;}return any;}bool SessionManager::all_clear()const{for(auto&s:slaves_)if(s.used&&s.faulted)return false;return true;}size_t SessionManager::pending_control()const{size_t n=0;for(auto&s:slaves_)for(auto&p:s.pending)if(p.active&&p.request_class==RequestClass::Control)++n;return n;}
size_t SessionManager::configured_count()const{size_t n=0;for(auto&s:slaves_)if(s.used)++n;return n;}size_t SessionManager::online_count()const{size_t n=0;for(auto&s:slaves_)if(s.used&&s.online&&!s.faulted)++n;return n;}
} // namespace master
