#include "master/show_controller.hpp"
namespace master {
bool ShowController::load(const PreparedMasterShow&s){if(state_!=ShowState::Idle||!validate_show(s)){state_=ShowState::Fault;return false;}show_=&s;return true;}
bool ShowController::prepare(){if(state_!=ShowState::Idle||!show_)return false;for(size_t i=0;i<show_->frame_count;i++)for(size_t b=0;b<show_->frames[i].batch_count;b++)if(!sessions_.add_slave(show_->frames[i].batches[b].slave_address)){fatal_fault();return false;}state_=ShowState::PreparingHello;for(uint16_t a=0;a<255;a++)if(sessions_.find(uint8_t(a))&&!sessions_.start_hello(uint8_t(a))){fatal_fault();return false;}return true;}
bool ShowController::start(){if(state_!=ShowState::Ready||!scheduler_slot_)return false;scheduler_slot_->start(*show_);state_=ShowState::Running;return true;}
bool ShowController::dispatch(const PreparedFrame&f){for(size_t b=0;b<f.batch_count;b++)if(!sessions_.send_updates(f.batches[b]))return false;return true;}
void ShowController::tick(){sessions_.service_timeouts();if(!sessions_.all_clear()&&(state_==ShowState::PreparingHello||state_==ShowState::PreparingReset)){fatal_fault();return;}if(state_==ShowState::PreparingHello&&sessions_.pending_control()==0){if(!sessions_.all_online()){fatal_fault();return;}state_=ShowState::PreparingReset;for(size_t i=0;i<show_->frame_count;i++)for(size_t b=0;b<show_->frames[i].batch_count;b++){auto a=show_->frames[i].batches[b].slave_address;bool first=true;for(size_t x=0;x<i;x++)for(size_t y=0;y<show_->frames[x].batch_count;y++)if(show_->frames[x].batches[y].slave_address==a)first=false;for(size_t y=0;y<b;y++)if(show_->frames[i].batches[y].slave_address==a)first=false;if(first&&!sessions_.send_reset(a)){fatal_fault();return;}}}else if(state_==ShowState::PreparingReset&&sessions_.pending_control()==0)state_=ShowState::Ready;else if(state_==ShowState::Running&&scheduler_slot_){if(!scheduler_slot_->tick())fatal_fault();else if(!scheduler_slot_->running())state_=ShowState::Ready;}else if(state_==ShowState::Stopping&&sessions_.pending_control()==0)state_=sessions_.all_clear()?ShowState::Idle:ShowState::Fault;}
void ShowController::stop(){if(state_==ShowState::Idle||state_==ShowState::Stopping)return;if(scheduler_slot_)scheduler_slot_->stop();state_=ShowState::Stopping;for(uint16_t a=0;a<255;a++)if(sessions_.find(uint8_t(a)))sessions_.send_reset(uint8_t(a));}
void ShowController::fatal_fault(){if(scheduler_slot_)scheduler_slot_->stop();state_=ShowState::Fault;for(uint16_t a=0;a<255;a++)if(sessions_.find(uint8_t(a)))sessions_.send_reset(uint8_t(a));}
} // namespace master
