import { describe, expect, it } from 'vitest';
import type { Project } from '../domain/project';
import type { CompiledShowV1 } from '../runtime/runtimeScore';
import { PreparationError, prepareCompiledShow, serializePreparedShow } from './prepareCompiledShow';

const at = '2026-01-01T00:00:00.000Z';
const project = (): Project => ({ schemaVersion: 3, id: 'p', name: 'Demo', createdAt: at, updatedAt: at, audio: null, score: { version: 1, events: [] }, deviceBindings: [], costumes: [{ id: 'costume', name: 'C', master: { id: 'master', displayName: 'M', type: 'esp32', slaves: [{ id: 'pico7', displayName: 'Pico 7', type: 'raspberry-pi-pico', logicalAddress: 7, channels: Array.from({ length: 4 }, (_, i) => ({ id: `ch${i}`, displayName: `Output ${i}`, type: 'el-wire' as const, hardwareOutputIdentifier: `GP${10 + i}`, protocolOutputId: i })) }, { id: 'pico8', displayName: 'Pico 8', type: 'raspberry-pi-pico', logicalAddress: 8, channels: [{ id: 'other', displayName: 'Other', type: 'el-wire', hardwareOutputIdentifier: 'relay', protocolOutputId: 0 }] }] } }] });
const transition = (channel: number, state: 'ON' | 'OFF' = 'ON') => ({ slaveId: 'pico7', slaveLogicalAddress: 7, channelId: `ch${channel}`, hardwareOutputIdentifier: `GP${10 + channel}`, state });
const compiled = (): CompiledShowV1 => ({ version: 1, durationMs: 2500, masters: [{ masterId: 'master', costumeId: 'costume', frames: [{ timeMs: 0, transitions: [transition(0)] }, { timeMs: 500, transitions: [transition(1)] }, { timeMs: 1000, transitions: [transition(2), transition(0, 'OFF')] }, { timeMs: 1500, transitions: [transition(2, 'OFF'), transition(1, 'OFF')] }, { timeMs: 2000, transitions: [transition(3)] }, { timeMs: 2500, transitions: [transition(3, 'OFF')] }] }] });
const error = (operation: () => unknown, code: PreparationError['code']) => { expect(operation).toThrowError(expect.objectContaining({ code })); };

describe('hardware preparation', () => {
  it('prepares an empty master and preserves duration', () => { const input = compiled(); input.masters[0].frames = []; expect(prepareCompiledShow(project(), input).masters[0]).toMatchObject({ durationMs: 2500, frames: [] }); });
  it('matches the ESP32 demo show semantics', () => { const result = prepareCompiledShow(project(), compiled()).masters[0]; expect(result.durationMs).toBe(2500); expect(result.frames.map(frame => [frame.timeMs, frame.slaveBatches[0].slaveAddress, frame.slaveBatches[0].updates])).toEqual([[0, 7, [{ outputId: 0, state: 'ON' }]], [500, 7, [{ outputId: 1, state: 'ON' }]], [1000, 7, [{ outputId: 0, state: 'OFF' }, { outputId: 2, state: 'ON' }]], [1500, 7, [{ outputId: 1, state: 'OFF' }, { outputId: 2, state: 'OFF' }]], [2000, 7, [{ outputId: 3, state: 'ON' }]], [2500, 7, [{ outputId: 3, state: 'OFF' }]]]); });
  it('sorts frames, batches and updates deterministically', () => { const input = compiled(); input.masters[0].frames = [{ timeMs: 20, transitions: [{ slaveId: 'pico8', slaveLogicalAddress: 8, channelId: 'other', hardwareOutputIdentifier: 'relay', state: 'ON' }, transition(2), transition(0)] }, { timeMs: 10, transitions: [transition(1)] }]; const a = prepareCompiledShow(project(), input); const b = prepareCompiledShow(project(), structuredClone(input)); expect(a).toEqual(b); expect(serializePreparedShow(a)).toBe(serializePreparedShow(b)); expect(a.masters[0].frames.map(f => f.timeMs)).toEqual([10, 20]); expect(a.masters[0].frames[1].slaveBatches.map(b => b.slaveAddress)).toEqual([7, 8]); expect(a.masters[0].frames[1].slaveBatches[0].updates.map(u => u.outputId)).toEqual([0, 2]); });
  it('reports missing mappings without returning a partial artifact', () => { const p = project(); delete p.costumes[0].master.slaves[0].channels[0].protocolOutputId; error(() => prepareCompiledShow(p, compiled()), 'missing-output-mapping'); });
  it('detects duplicate and invalid mappings', () => { const duplicate = project(); duplicate.costumes[0].master.slaves[0].channels[1].protocolOutputId = 0; error(() => prepareCompiledShow(duplicate, compiled()), 'duplicate-output-id'); const invalid = project(); invalid.costumes[0].master.slaves[0].channels[0].protocolOutputId = 256; error(() => prepareCompiledShow(invalid, compiled()), 'invalid-output-id'); });
  it.each([255, 256])('rejects Protocol v1 slave address %s', address => { const p = project(); p.costumes[0].master.slaves[0].logicalAddress = address; error(() => prepareCompiledShow(p, compiled()), 'invalid-slave-address'); });
  it('detects missing channels, slave mismatch, target changes and invalid time/state', () => { const missing = compiled(); missing.masters[0].frames[0].transitions[0].channelId = 'missing'; error(() => prepareCompiledShow(project(), missing), 'missing-channel'); const slave = compiled(); slave.masters[0].frames[0].transitions[0].slaveId = 'pico8'; error(() => prepareCompiledShow(project(), slave), 'channel-slave-mismatch'); const target = compiled(); target.masters[0].frames[0].transitions[0].hardwareOutputIdentifier = 'GP99'; error(() => prepareCompiledShow(project(), target), 'target-mismatch'); const time = compiled(); time.masters[0].frames[0].timeMs = -1; error(() => prepareCompiledShow(project(), time), 'invalid-time'); const state = compiled(); (state.masters[0].frames[0].transitions[0] as { state: string }).state = 'BLINK'; error(() => prepareCompiledShow(project(), state), 'unsupported-state'); });
  it('rejects more than one Protocol v1 payload worth of simultaneous updates', () => { const p = project(); p.costumes[0].master.slaves[0].channels = Array.from({ length: 32 }, (_, i) => ({ id: `x${i}`, displayName: `X${i}`, type: 'el-wire' as const, hardwareOutputIdentifier: `wire-${i}`, protocolOutputId: i })); const input = compiled(); input.masters[0].frames = [{ timeMs: 0, transitions: p.costumes[0].master.slaves[0].channels.map(c => ({ slaveId: 'pico7', slaveLogicalAddress: 7, channelId: c.id, hardwareOutputIdentifier: c.hardwareOutputIdentifier, state: 'ON' as const })) }]; error(() => prepareCompiledShow(p, input), 'too-many-simultaneous-updates'); });
});
