#include "pico_slave/command_processor.hpp"
#include <array>
namespace pico_slave {
bool CommandProcessor::initialize(){return outputs_.initialize()&&outputs_.resetAll();}
CommandResult CommandProcessor::process(const Frame&r){if(r.slave_address!=slave_address_||r.slave_address==255)return CommandResult::Ignored;if(r.version!=kProtocolVersion){++counters_.invalidFrames;return CommandResult::Invalid;}uint8_t signature[2+kMaxPayload];signature[0]=r.message_type;signature[1]=uint8_t(r.payload_length);for(size_t i=0;i<r.payload_length;i++)signature[2+i]=r.payload[i];const auto fingerprint=crc16CcittFalse(signature,2+r.payload_length);if(duplicate_valid_&&r.session_id==last_session_&&r.sequence==last_sequence_&&fingerprint==last_fingerprint_){++counters_.validFrames;return CommandResult::Duplicate;}
 const auto type=static_cast<MessageType>(r.message_type);if(type==MessageType::ResetOutputs){if(r.payload_length!=0||!outputs_.resetAll()){++counters_.invalidFrames;return CommandResult::Invalid;}++counters_.validFrames;++counters_.resetCommandsApplied;duplicate_valid_=true;last_session_=r.session_id;last_sequence_=r.sequence;last_fingerprint_=fingerprint;return CommandResult::ResetApplied;}
 if(type!=MessageType::SetOutputs||r.payload_length<3||r.payload[0]==0||r.payload[0]>31||r.payload_length!=1+2*r.payload[0]){++counters_.invalidFrames;return CommandResult::Invalid;}
 std::array<OutputUpdate,31>updates{};std::array<bool,256>seen{};for(uint8_t i=0;i<r.payload[0];i++){auto id=r.payload[1+2*i],state=r.payload[2+2*i];if(seen[id]||!outputs_.validateOutput(id)||state>1){++counters_.invalidFrames;return CommandResult::Invalid;}seen[id]=true;updates[i]={id,state==1};}if(!outputs_.applyBatch(updates.data(),r.payload[0])){++counters_.invalidFrames;return CommandResult::Invalid;}++counters_.validFrames;++counters_.setCommandsApplied;duplicate_valid_=true;last_session_=r.session_id;last_sequence_=r.sequence;last_fingerprint_=fingerprint;return CommandResult::SetApplied;}
}
