import { activateShow, beginUpload, endUpload, getStatus, hello, startShow, stopShow, uploadChunk } from './messages';
import { DESKTOP_MAX_PAYLOAD_SIZE, DesktopFrameParser, DesktopMessageType as M, DeviceState, encodeDesktopFrame, hex, incrementDesktopSequence, type DesktopFrame } from './protocol';
import { serializePreparedMasterShowBinary } from './preparedBinary';
import { sha256 } from './sha256';
import type { PreparedMasterShowV1 } from '../preparation/preparedShow';
import type { DesktopEsp32Transport, DesktopTransportError, SerialPortDescriptor } from './transport';

export const HELLO_TIMEOUT_MS=1000, REQUEST_TIMEOUT_MS=750, REQUEST_RETRIES=2;
export type ConnectionPhase='Disconnected'|'Connecting'|'Handshaking'|'Connected'|'Uploading'|'Error';
export interface DeviceIdentity {deviceId:string;firmwareVersion:string;protocolVersion:number;deviceState:DeviceState}
export interface DeviceStatus {deviceState:DeviceState;activeArtifact?:string;candidateArtifact?:string;durationMs:number;positionMs:number;picoOnline:number;picoConfigured:number;fault:number;faultDetail:number;lateFrames:number;maxLatenessUs:number}
export class ConnectionError extends Error {constructor(readonly code:'HandshakeTimeout'|'ProtocolError'|'Disconnected'|'RequestTimeout'|'Cancelled',message:string){super(message);this.name='ConnectionError';}}
type Pending={bytes:Uint8Array;expected:Set<number>;resolve:(f:DesktopFrame)=>void;reject:(e:Error)=>void;timer?:ReturnType<typeof setTimeout>;attempt:number};
export class DesktopEsp32Connection {
 phase:ConnectionPhase='Disconnected';identity?:DeviceIdentity;status?:DeviceStatus;port?:string;uploadProgress?:{sent:number;total:number};lastError?:Error;
 private parser=new DesktopFrameParser();private sequence=0;private sessionId=0;private pending=new Map<number,Pending>();private cancelled=false;private removeBytes?:()=>void;private removeDisconnect?:()=>void;
 constructor(readonly transport:DesktopEsp32Transport,private readonly randomSession=()=>crypto.getRandomValues(new Uint32Array(1))[0]){}
 listPorts():Promise<SerialPortDescriptor[]>{return this.transport.listPorts();}
 async connect(port:string){if(this.phase!=='Disconnected'&&this.phase!=='Error')await this.disconnect();this.phase='Connecting';this.port=port;this.lastError=undefined;this.parser.reset();this.sequence=0;this.sessionId=this.randomSession()>>>0;this.removeBytes=this.transport.onBytes(b=>this.ingest(b));this.removeDisconnect=this.transport.onDisconnect(e=>this.failDisconnect(e));try{await this.transport.open(port);this.phase='Handshaking';const frame=await this.request(s=>hello(s,this.sessionId),new Set([M.HELLO_ACK]),HELLO_TIMEOUT_MS,0);this.identity=parseHello(frame);this.phase='Connected';await this.refreshStatus();}catch(e){this.phase='Error';this.lastError=e instanceof Error?e:new Error(String(e));this.rejectAll(this.lastError);await this.transport.close().catch(()=>{});throw this.lastError;}}
 async disconnect(){this.cancelled=true;this.rejectAll(new ConnectionError('Disconnected','Connection closed.'));await this.transport.close().catch(()=>{});this.cleanup();this.phase='Disconnected';this.identity=undefined;this.status=undefined;this.port=undefined;this.uploadProgress=undefined;}
 async refreshStatus(){const frame=await this.request(s=>getStatus(s,this.sessionId),new Set([M.STATUS]));this.status=parseStatus(frame);if(this.identity)this.identity.deviceState=this.status.deviceState;return this.status;}
 async uploadAndActivate(show:PreparedMasterShowV1,onProgress?:(sent:number,total:number)=>void){this.requireConnected();if(this.status?.deviceState===DeviceState.RUNNING)throw new Error('Upload is disabled while the device is RUNNING.');const bytes=serializePreparedMasterShowBinary(show),hashBytes=sha256(bytes);this.cancelled=false;this.phase='Uploading';this.uploadProgress={sent:0,total:bytes.length};try{const ready=await this.request(s=>beginUpload(s,this.sessionId,bytes.length,hashBytes),new Set([M.UPLOAD_READY]));const max=new DataView(ready.payload.buffer,ready.payload.byteOffset).getUint16(4,true);const chunkSize=Math.min(DESKTOP_MAX_PAYLOAD_SIZE-4,max);if(chunkSize<1)throw new ConnectionError('ProtocolError','Device returned an invalid chunk size.');for(let offset=0;offset<bytes.length;offset+=chunkSize){if(this.cancelled)throw new ConnectionError('Cancelled','Upload cancelled.');const data=bytes.slice(offset,offset+chunkSize);await this.request(s=>uploadChunk(s,this.sessionId,offset,data),new Set([M.ACK]));this.uploadProgress={sent:offset+data.length,total:bytes.length};onProgress?.(offset+data.length,bytes.length);}const complete=await this.request(s=>endUpload(s,this.sessionId),new Set([M.UPLOAD_COMPLETE]));if(hex(complete.payload)!==hex(hashBytes))throw new ConnectionError('ProtocolError','UPLOAD_COMPLETE artifact hash mismatch.');await this.request(s=>activateShow(s,this.sessionId,hashBytes),new Set([M.ACK]));const status=await this.refreshStatus();if(status.activeArtifact!==hex(hashBytes))throw new ConnectionError('ProtocolError','Activated artifact was not confirmed by STATUS.');return status;}finally{if(this.phase==='Uploading')this.phase='Connected';}}
 async cancelUpload(){this.cancelled=true;await this.disconnect();}
 async start(){this.requireConnected();if(!this.status?.activeArtifact||this.status.fault!==0)throw new Error('Start requires an active artifact and a fault-free device.');await this.request(s=>startShow(s,this.sessionId),new Set([M.ACK]));return this.refreshStatus();}
 async stop(){this.requireConnected();await this.request(s=>stopShow(s,this.sessionId),new Set([M.ACK]));return this.refreshStatus();}
 private request(factory:(sequence:number)=>DesktopFrame,expected:Set<number>,timeout=REQUEST_TIMEOUT_MS,retries=REQUEST_RETRIES){const sequence=this.sequence;this.sequence=incrementDesktopSequence(this.sequence);const bytes=encodeDesktopFrame(factory(sequence));return new Promise<DesktopFrame>((resolve,reject)=>{const item:Pending={bytes,expected,resolve,reject,attempt:0};this.pending.set(sequence,item);this.sendAttempt(sequence,item,timeout,retries);});}
 private sendAttempt(sequence:number,item:Pending,timeout:number,retries:number){void this.transport.write(item.bytes).then(()=>{item.timer=setTimeout(()=>{if(!this.pending.has(sequence))return;if(item.attempt++<retries){this.sendAttempt(sequence,item,timeout,retries);return;}this.pending.delete(sequence);item.reject(new ConnectionError(item.expected.has(M.HELLO_ACK)?'HandshakeTimeout':'RequestTimeout',`Request ${sequence} timed out.`));},timeout);}).catch(e=>{this.pending.delete(sequence);item.reject(e);});}
 private ingest(bytes:Uint8Array){for(const event of this.parser.push(bytes)){if(event.kind==='error'){this.lastError=new ConnectionError('ProtocolError',`Malformed serial frame: ${event.code}`);continue;}const p=this.pending.get(event.frame.sequence);if(!p||event.frame.sessionId!==this.sessionId)continue;if(event.frame.messageType===M.NACK){this.finish(event.frame.sequence,p);p.reject(new ConnectionError('ProtocolError',`Device NACK ${event.frame.payload[0]??'unknown'}.`));}else if(p.expected.has(event.frame.messageType)){this.finish(event.frame.sequence,p);p.resolve(event.frame);}}}
 private finish(sequence:number,p:Pending){if(p.timer)clearTimeout(p.timer);this.pending.delete(sequence);}
 private failDisconnect(e:DesktopTransportError){this.lastError=e;this.rejectAll(new ConnectionError('Disconnected',e.message));this.cleanup();this.phase='Error';}
 private rejectAll(e:Error){for(const p of this.pending.values()){if(p.timer)clearTimeout(p.timer);p.reject(e);}this.pending.clear();}
 private cleanup(){this.removeBytes?.();this.removeDisconnect?.();this.removeBytes=this.removeDisconnect=undefined;this.parser.reset();}
 private requireConnected(){if(this.phase!=='Connected')throw new ConnectionError('Disconnected','ESP32 is not connected.');}
}
function parseHello(f:DesktopFrame):DeviceIdentity{if(f.payload.length!==22||f.payload[0]!==1)throw new ConnectionError('ProtocolError','Invalid HELLO_ACK.');return{protocolVersion:f.payload[0],deviceId:hex(f.payload.slice(1,17)),firmwareVersion:`${f.payload[17]}.${f.payload[18]}.${f.payload[19]}`,deviceState:f.payload[20] as DeviceState};}
function parseStatus(f:DesktopFrame):DeviceStatus{if(f.payload.length!==91)throw new ConnectionError('ProtocolError','Invalid STATUS.');const p=f.payload,v=new DataView(p.buffer,p.byteOffset,p.byteLength);return{deviceState:p[0] as DeviceState,activeArtifact:p[1]?hex(p.slice(2,34)):undefined,candidateArtifact:p[34]?hex(p.slice(35,67)):undefined,durationMs:v.getUint32(67,true),positionMs:v.getUint32(71,true),picoOnline:p[75],picoConfigured:p[76],fault:p[77],faultDetail:v.getUint16(78,true),lateFrames:v.getUint32(80,true),maxLatenessUs:v.getUint32(84,true)};}
export const compareArtifacts=(local:string|undefined,device:string|undefined):'Match'|'Different'|'No local artifact'=>!local?'No local artifact':local===device?'Match':'Different';
