import { deserializePreparedMasterShowBinary } from './preparedBinary';
import { sha256 } from './sha256';
import { DesktopMessageType as M, DesktopNackCode as N, DeviceState, FaultCategory, MAX_PREPARED_SHOW_SIZE, type DesktopFrame, requestFrame } from './protocol';

interface Artifact { bytes:Uint8Array; hash:Uint8Array; durationMs:number }
interface Upload { bytes:Uint8Array; expectedHash:Uint8Array; received:number }
const equal=(a:Uint8Array,b:Uint8Array)=>a.length===b.length&&a.every((x,i)=>x===b[i]);
/** Pure executable specification. It performs no I/O and models volatile storage only. */
export class ReferenceEsp32Device {
 readonly deviceId:Uint8Array; state=DeviceState.IDLE; sessionId:number|undefined; active?:Artifact; candidate?:Artifact; private upload?:Upload; private replay=new Map<number,DesktopFrame>(); startCount=0; connectedPicos=0; requiredPicos=0; lateFrameCount=0; maxLatenessUs=0; showPositionMs=0; fault=FaultCategory.NONE; faultDetail=0;
 constructor(deviceId=new Uint8Array(16).fill(0x11),readonly firmwareVersion:[number,number,number]=[1,0,0]){if(deviceId.length!==16)throw new Error('deviceId must be 128 bits.');this.deviceId=deviceId.slice();}
 handle(req:DesktopFrame):DesktopFrame {if(req.messageType===M.HELLO)return this.onHello(req);if(this.sessionId===undefined||req.sessionId!==this.sessionId)return this.nack(req,N.BAD_SESSION);const old=this.replay.get(req.sequence);if(old)return old;let result:DesktopFrame;try{result=this.dispatch(req);}catch{result=this.nack(req,N.INVALID_PAYLOAD);}this.replay.set(req.sequence,result);return result;}
 disconnect():void{/* Deliberately preserves RUNNING and all stored shows. */}
 private onHello(r:DesktopFrame){if(r.payload.length!==1||r.payload[0]!==1)return this.nack(r,N.UNSUPPORTED_VERSION);this.sessionId=r.sessionId;this.replay.clear();this.upload=undefined;if(this.state===DeviceState.UPLOADING)this.state=this.active?DeviceState.READY:DeviceState.IDLE;const p=new Uint8Array(22);p[0]=1;p.set(this.deviceId,1);p.set(this.firmwareVersion,17);p[20]=this.state;p[21]=0;return this.res(r,M.HELLO_ACK,p);}
 private dispatch(r:DesktopFrame):DesktopFrame {switch(r.messageType){case M.BEGIN_UPLOAD:return this.begin(r);case M.UPLOAD_CHUNK:return this.chunk(r);case M.END_UPLOAD:return this.end(r);case M.ACTIVATE_SHOW:return this.activate(r);case M.START_SHOW:return this.start(r);case M.STOP_SHOW:return this.stop(r);case M.GET_STATUS:return this.status(r);default:return this.nack(r,N.UNKNOWN_MESSAGE);}}
 private begin(r:DesktopFrame){if(this.state===DeviceState.RUNNING)return this.nack(r,N.BUSY);if(r.payload.length!==37||r.payload[0]!==1)return this.nack(r,N.INVALID_PAYLOAD);const length=new DataView(r.payload.buffer,r.payload.byteOffset).getUint32(1,true);if(length>MAX_PREPARED_SHOW_SIZE)return this.nack(r,N.UPLOAD_TOO_LARGE);this.upload={bytes:new Uint8Array(length),expectedHash:r.payload.slice(5),received:0};this.state=DeviceState.UPLOADING;const p=new Uint8Array(6);new DataView(p.buffer).setUint32(0,length,true);new DataView(p.buffer).setUint16(4,1020,true);return this.res(r,M.UPLOAD_READY,p);}
 private chunk(r:DesktopFrame){if(this.state!==DeviceState.UPLOADING||!this.upload)return this.nack(r,N.INVALID_STATE);if(r.payload.length<5)return this.nack(r,N.INVALID_PAYLOAD);const offset=new DataView(r.payload.buffer,r.payload.byteOffset).getUint32(0,true),data=r.payload.subarray(4),u=this.upload;if(offset<u.received){if(offset+data.length<=u.received&&equal(u.bytes.subarray(offset,offset+data.length),data))return this.res(r,M.ACK);return this.nack(r,N.UPLOAD_CONFLICT);}if(offset!==u.received||offset+data.length>u.bytes.length)return this.nack(r,N.UPLOAD_OFFSET);u.bytes.set(data,offset);u.received+=data.length;return this.res(r,M.ACK);}
 private end(r:DesktopFrame){const u=this.upload;if(this.state!==DeviceState.UPLOADING||!u)return this.nack(r,N.INVALID_STATE);if(u.received!==u.bytes.length)return this.nack(r,N.UPLOAD_OFFSET);const hash=sha256(u.bytes);if(!equal(hash,u.expectedHash)){this.abortUpload();return this.nack(r,N.HASH_MISMATCH);}let durationMs:number;try{durationMs=deserializePreparedMasterShowBinary(u.bytes).durationMs;}catch{this.abortUpload();return this.nack(r,N.INVALID_SHOW);}this.candidate={bytes:u.bytes.slice(),hash,durationMs};this.upload=undefined;this.state=this.active?DeviceState.READY:DeviceState.IDLE;return this.res(r,M.UPLOAD_COMPLETE,hash);}
 private activate(r:DesktopFrame){if(this.state===DeviceState.RUNNING||this.state===DeviceState.UPLOADING)return this.nack(r,N.INVALID_STATE);if(!this.candidate||r.payload.length!==32||!equal(r.payload,this.candidate.hash))return this.nack(r,N.NO_SHOW);this.active=this.candidate;this.candidate=undefined;this.state=DeviceState.READY;return this.res(r,M.ACK);}
 private start(r:DesktopFrame){if(this.state===DeviceState.RUNNING)return this.res(r,M.ACK);if(this.state===DeviceState.UPLOADING)return this.nack(r,N.INVALID_STATE);if(!this.active)return this.nack(r,N.NO_SHOW);this.state=DeviceState.RUNNING;this.showPositionMs=0;this.startCount++;return this.res(r,M.ACK);}
 private stop(r:DesktopFrame){if(this.state===DeviceState.UPLOADING)return this.nack(r,N.INVALID_STATE);this.state=this.active?DeviceState.READY:DeviceState.IDLE;this.showPositionMs=0;return this.res(r,M.ACK);}
 private status(r:DesktopFrame){const p=new Uint8Array(91),v=new DataView(p.buffer);p[0]=this.state;p[1]=this.active?1:0;if(this.active)p.set(this.active.hash,2);p[34]=this.candidate?1:0;if(this.candidate)p.set(this.candidate.hash,35);v.setUint32(67,this.active?.durationMs??0,true);v.setUint32(71,this.state===DeviceState.RUNNING?this.showPositionMs:0,true);p[75]=this.connectedPicos;p[76]=this.requiredPicos;p[77]=this.fault;v.setUint16(78,this.faultDetail,true);v.setUint32(80,this.lateFrameCount,true);v.setUint32(84,this.maxLatenessUs,true);v.setUint16(88,0,true);p[90]=1;return this.res(r,M.STATUS,p);}
 private abortUpload(){this.upload=undefined;this.state=this.active?DeviceState.READY:DeviceState.IDLE;}
 private res(r:DesktopFrame,t:number,p:Uint8Array=new Uint8Array()){return requestFrame(t,r.sequence,r.sessionId,p);}private nack(r:DesktopFrame,n:N){return this.res(r,M.NACK,new Uint8Array([n]));}
}
