import { useCallback, useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent, type UIEvent } from 'react';
import { Minus, Plus } from 'lucide-react';
import { formatTimelineTime, timelineTime, type TimelineTimeMs } from '../../domain/timelineTime';
import type { EntityId } from '../../domain/project';
import type { LightInterval } from '../../score/score';
import { buildScoreLaneModel } from '../../score/scoreLaneModel';
import { calculateCreation, calculateResize, type IntervalRange } from '../../timeline/scoreInteraction';
import { chooseTickInterval, fitPixelsPerSecond, formatRulerTime, MAX_PIXELS_PER_SECOND, MIN_PIXELS_PER_SECOND, timeToX, xToTime } from '../../timeline/timelineViewport';
import { useAppState } from '../state/AppState';
import { WaveformCanvas } from './WaveformCanvas';
import { snapTime } from '../../timeline/snapping';

type Drag = { pointerId: number; kind: 'create' | 'move' | 'resize-start' | 'resize-end'; channelId: string; event?: LightInterval; group: LightInterval[]; originX: number; originTime: TimelineTimeMs; preview: IntervalRange | null; previews: Map<string, IntervalRange>; deltaMs: number; invalid: boolean };

export function TimelineSurface({ projectId, selectedEventIds, onSelectEvents, snapEnabled, gridMs, onSnapEnabled, onGridMs }: { projectId: string; selectedEventIds: ReadonlySet<EntityId>; onSelectEvents: (ids: Set<EntityId>) => void; snapEnabled: boolean; gridMs: number; onSnapEnabled: (enabled: boolean) => void; onGridMs: (grid: number) => void }) {
  const { project, audio, score } = useAppState(); const persistedDuration = project?.audio?.durationMs ?? 0; const duration = audio.transport.durationMs || persistedDuration || 10_000;
  const viewportRef = useRef<HTMLDivElement>(null); const labelScrollRef = useRef<HTMLDivElement>(null); const [width, setWidth] = useState(0); const [scale, setScale] = useState(80); const [scrollLeft, setScrollLeft] = useState(0); const [fit, setFit] = useState(true); const [hover, setHover] = useState<number | null>(null); const [seeking, setSeeking] = useState(false); const [drag, setDrag] = useState<Drag | null>(null); const manualScrollUntil = useRef(0);
  const lanes = useMemo(() => project ? buildScoreLaneModel(project) : [], [project]);
  useEffect(() => { setScrollLeft(0); setFit(true); setHover(null); setDrag(null); onSelectEvents(new Set()); }, [projectId]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { const node = viewportRef.current; if (!node) return; setWidth(Math.round(node.getBoundingClientRect().width)); if (!globalThis.ResizeObserver) return; const observer = new ResizeObserver(entries => setWidth(Math.round(entries[0].contentRect.width))); observer.observe(node); return () => observer.disconnect(); }, []);
  const fitted = fitPixelsPerSecond(width, duration); const pixelsPerSecond = fit ? fitted : scale; const contentWidth = Math.max(width, duration / 1_000 * pixelsPerSecond); const viewport = useMemo(() => ({ pixelsPerSecond, scrollLeft }), [pixelsPerSecond, scrollLeft]);
  useEffect(() => { if (fit) { scrollElement(viewportRef.current, 0); setScrollLeft(0); } }, [fit, fitted]);
  useEffect(() => { if (audio.transport.status !== 'playing' || Date.now() < manualScrollUntil.current || !viewportRef.current) return; const x = timeToX(audio.transport.currentTimeMs, viewport); if (x > width * .82) scrollElement(viewportRef.current, Math.min(contentWidth - width, scrollLeft + width * .55), true); }, [audio.transport.currentTimeMs, audio.transport.status, contentWidth, scrollLeft, viewport, width]);
  const clientTime = useCallback((clientX: number) => { const rect = viewportRef.current?.getBoundingClientRect(); return xToTime(clientX - (rect?.left ?? 0), { pixelsPerSecond, scrollLeft }, duration); }, [duration, pixelsPerSecond, scrollLeft]);
  const seekAt = (clientX: number) => audio.seek(clientTime(clientX));
  const zoom = (factor: number) => { const old = pixelsPerSecond; const next = Math.min(MAX_PIXELS_PER_SECOND, Math.max(MIN_PIXELS_PER_SECOND, old * factor)); const centerTime = (scrollLeft + width / 2) / old; setFit(false); setScale(next); requestAnimationFrame(() => scrollElement(viewportRef.current, Math.max(0, centerTime * next - width / 2))); };
  const tick = chooseTickInterval(pixelsPerSecond); const firstTick = Math.ceil(scrollLeft / pixelsPerSecond * 1_000 / tick) * tick; const ticks = []; for (let time = firstTick; time <= duration && timeToX(timelineTime(time), viewport) <= width; time += tick) ticks.push(time);
  const beginDrag = (event: ReactPointerEvent, kind: Drag['kind'], channelId: string, item?: LightInterval) => { event.stopPropagation(); audio.pause(); event.currentTarget.setPointerCapture(event.pointerId); const originTime = clientTime(event.clientX); let group: LightInterval[] = []; if (item) { const keepGroup = selectedEventIds.has(item.id); group = keepGroup ? project!.score.events.filter(value => selectedEventIds.has(value.id)) : [item]; if (!keepGroup) onSelectEvents(new Set([item.id])); } setDrag({ pointerId: event.pointerId, kind, channelId, event: item, group, originX: event.clientX, originTime, preview: item ? { startMs: item.startMs, endMs: item.endMs } : null, previews: new Map(), deltaMs: 0, invalid: false }); };
  const updateDrag = (event: ReactPointerEvent) => { if (!drag || event.pointerId !== drag.pointerId || !project) return; const rawNow = clientTime(event.clientX); const now = snapEnabled && !event.altKey ? snapTime(rawNow, gridMs) : rawNow; let preview: IntervalRange | null; const previews = new Map<string, IntervalRange>(); let deltaMs = 0;
    if (drag.kind === 'create') { const origin = snapEnabled && !event.altKey ? snapTime(drag.originTime, gridMs) : drag.originTime; preview = calculateCreation(origin, now, event.clientX - drag.originX); }
    else if (drag.kind === 'move') { const earliest = Math.min(...drag.group.map(item => item.startMs)); const latest = Math.max(...drag.group.map(item => item.endMs)); let requested = drag.event!.startMs + now - drag.originTime; if (snapEnabled && !event.altKey) requested = snapTime(requested, gridMs); deltaMs = requested - drag.event!.startMs; const maximumDelta = project.audio?.durationMs === undefined ? Number.MAX_SAFE_INTEGER : project.audio.durationMs - latest; deltaMs = Math.max(-earliest, Math.min(deltaMs, maximumDelta)); for (const item of drag.group) previews.set(item.id, { startMs: item.startMs + deltaMs, endMs: item.endMs + deltaMs }); preview = previews.get(drag.event!.id)!; }
    else preview = calculateResize(drag.event!, drag.kind === 'resize-start' ? 'start' : 'end', now, timelineTime(duration));
    const selected = new Set(drag.group.map(item => item.id)); const candidates = drag.kind === 'move' ? [...previews.entries()] : preview && drag.event ? [[drag.event.id, preview] as const] : []; const invalid = candidates.some(([id, range]) => { const item = project.score.events.find(value => value.id === id)!; return project.score.events.some(other => !selected.has(other.id) && other.channelId === item.channelId && range.startMs < other.endMs && other.startMs < range.endMs); }); setDrag({ ...drag, preview, previews, deltaMs, invalid }); };
  const endDrag = (event: ReactPointerEvent) => { if (!drag || event.pointerId !== drag.pointerId) return; event.currentTarget.releasePointerCapture?.(event.pointerId); const changed = drag.kind === 'create' || (drag.preview && drag.event && (drag.preview.startMs !== drag.event.startMs || drag.preview.endMs !== drag.event.endMs)); if (drag.preview && !drag.invalid && changed) { if (drag.kind === 'create') score.add({ channelId: drag.channelId, ...drag.preview }); else if (drag.kind === 'move') score.moveMany(drag.group.map(item => item.id), drag.deltaMs); else score.resize(drag.event!.id, drag.kind === 'resize-start' ? { startMs: drag.preview.startMs } : { endMs: drag.preview.endMs }); } setDrag(null); };
  const pointerMove = (event: ReactPointerEvent) => { setHover(clientTime(event.clientX)); if (seeking) seekAt(event.clientX); updateDrag(event); };
  return <section className="timeline-surface" aria-label="Show timeline">
    <div className="timeline-controls"><span>{Math.round(pixelsPerSecond)} px/s</span><button aria-label="Zoom out" onClick={() => zoom(.7)}><Minus size={14}/></button><button aria-label="Zoom in" onClick={() => zoom(1.4)}><Plus size={14}/></button><button onClick={() => setFit(true)}>Fit</button><label><input type="checkbox" checked={snapEnabled} onChange={event => onSnapEnabled(event.target.checked)}/> Snap</label><label>Grid <select aria-label="Snap grid" value={gridMs} disabled={!snapEnabled} onChange={event => onGridMs(Number(event.target.value))}>{[10,25,50,100,250,500,1000].map(value => <option key={value} value={value}>{value === 1000 ? '1 s' : `${value} ms`}</option>)}</select></label></div>
    <div className="timeline-layout">
      <div className="timeline-label-header">TIME</div><div className="timeline-scroll" ref={viewportRef} data-testid="timeline-scroll" onScroll={(event: UIEvent<HTMLDivElement>) => { setScrollLeft(event.currentTarget.scrollLeft); manualScrollUntil.current = Date.now() + 1_500; }}>
        <div className="timeline-content" style={{ width: contentWidth }} onPointerMove={pointerMove} onPointerUp={endDrag} onPointerCancel={() => setDrag(null)} onPointerLeave={() => { if (!seeking && !drag) setHover(null); }}>
          <div className="time-ruler" onPointerDown={event => { event.currentTarget.setPointerCapture(event.pointerId); setSeeking(true); seekAt(event.clientX); }} onPointerUp={() => setSeeking(false)}>{ticks.map(time => <span key={time} style={{ left: time / 1_000 * pixelsPerSecond }}><i/>{formatRulerTime(timelineTime(time), tick)}</span>)}</div>
          <div className="waveform-area" onPointerDown={event => { event.currentTarget.setPointerCapture(event.pointerId); setSeeking(true); seekAt(event.clientX); }}>{audio.waveform.status === 'loading' && <div className="waveform-message">Analyzing audio…</div>}{audio.waveform.status === 'error' && <div className="waveform-message error">Waveform unavailable</div>}{audio.waveform.data && <WaveformCanvas data={audio.waveform.data} width={width} height={120} contentWidth={contentWidth} scrollLeft={scrollLeft}/>}</div>
          <div className="score-lanes" onScroll={event => { if (labelScrollRef.current) labelScrollRef.current.scrollTop = event.currentTarget.scrollTop; }}>
            {lanes.map(lane => <div className="score-lane" data-channel-id={lane.channel.id} key={lane.channel.id} onPointerDown={event => { if (event.button === 0) { onSelectEvents(new Set()); beginDrag(event, 'create', lane.channel.id); } }}>
              {lane.events.map(item => { const preview = drag?.previews.get(item.id) ?? (drag?.event?.id === item.id ? drag.preview : null); const range = preview ?? item; const selected = selectedEventIds.has(item.id); return <button type="button" className={`score-event${selected ? ' selected' : ''}${preview && drag?.invalid ? ' invalid' : ''}`} key={item.id} aria-label={`${lane.channel.displayName} light interval, ${formatTimelineTime(item.startMs)} to ${formatTimelineTime(item.endMs)}`} aria-pressed={selected} style={{ left: range.startMs / 1_000 * pixelsPerSecond, width: Math.max(2, (range.endMs - range.startMs) / 1_000 * pixelsPerSecond) }} onClick={event => { event.stopPropagation(); if (event.ctrlKey || event.metaKey) { const next = new Set(selectedEventIds); if (next.has(item.id)) next.delete(item.id); else next.add(item.id); onSelectEvents(next); } else onSelectEvents(new Set([item.id])); }} onPointerDown={event => { if (event.ctrlKey || event.metaKey) event.stopPropagation(); else beginDrag(event, 'move', lane.channel.id, item); }}>{selected && selectedEventIds.size === 1 && <><i className="resize-handle left" aria-hidden onPointerDown={event => beginDrag(event, 'resize-start', lane.channel.id, item)}/><i className="resize-handle right" aria-hidden onPointerDown={event => beginDrag(event, 'resize-end', lane.channel.id, item)}/></>}</button>; })}
              {drag?.kind === 'create' && drag.channelId === lane.channel.id && drag.preview && <div className={`score-event preview${drag.invalid ? ' invalid' : ''}`} style={{ left: drag.preview.startMs / 1_000 * pixelsPerSecond, width: Math.max(2, (drag.preview.endMs - drag.preview.startMs) / 1_000 * pixelsPerSecond) }}/>}
            </div>)}
          </div>
          <div className="playhead score-playhead" aria-label="Playhead" style={{ left: audio.transport.currentTimeMs / 1_000 * pixelsPerSecond }}/>{hover !== null && <div className="hover-time timeline-hover" style={{ left: hover / 1_000 * pixelsPerSecond }}>{formatRulerTime(timelineTime(hover), timelineTime(1))}</div>}
        </div>
      </div>
      <div className="waveform-label">WAVEFORM</div><div className="score-labels" ref={labelScrollRef}>{lanes.length ? lanes.map(lane => { const costume = project!.costumes.find(value => value.id === lane.costumeId)!; const pico = costume.master.slaves.find(value => value.id === lane.controllerId)!; return <div className="score-label" key={lane.channel.id}><strong>Channel: {lane.channel.displayName}</strong><span>{costume.name} / {pico.displayName} · {lane.channel.type}</span></div>; }) : <div className="score-no-channels">Add output channels to the costume before creating score events.</div>}</div>
    </div>
  </section>;
}
function scrollElement(element: HTMLDivElement | null, left: number, smooth = false) { if (!element) return; if (typeof element.scrollTo === 'function') element.scrollTo({ left, behavior: smooth ? 'smooth' : 'auto' }); else element.scrollLeft = left; }
