import { Activity, Cable, Cpu, RefreshCw } from 'lucide-react';
import { useMemo, useState, type ReactNode } from 'react';
import { DeviceState, hex } from '../../desktopEsp32/protocol';
import { compareArtifacts } from '../../desktopEsp32/connection';
import { serializePreparedMasterShowBinary } from '../../desktopEsp32/preparedBinary';
import { sha256 } from '../../desktopEsp32/sha256';
import { useAppState } from '../state/AppState';

const short=(value?:string)=>value?`${value.slice(0,12)}…`:'—';
export function DevicesPage() {
 const app=useAppState(),{connection,ports}=app.hardware,[selectedPort,setSelectedPort]=useState(''),[masterId,setMasterId]=useState(''),[connectionType,setConnectionType]=useState<'serial'|'network'>('serial'),[host,setHost]=useState('192.168.1.123'),[port,setPort]=useState(3333),[netSsid,setNetSsid]=useState(''),[netPassword,setNetPassword]=useState(''),[changePassword,setChangePassword]=useState(false),[netPort,setNetPort]=useState(3333),[firmware,setFirmware]=useState<{name:string;bytes:Uint8Array;hash:string}|null>(null),[message,setMessage]=useState('');
 const masters=app.project?.costumes.map(c=>({costume:c.name,master:c.master}))??[];
 const binding=app.project?.deviceBindings.find(b=>b.physicalDevice.type==='esp32'&&b.physicalDevice.hardwareId.toLowerCase()===connection.identity?.deviceId);
 const bound=masters.find(m=>m.master.id===binding?.logicalControllerId),prepared=app.preparation.result?.masters.find(m=>m.masterId===binding?.logicalControllerId);
 const localHash=useMemo(()=>prepared?hex(sha256(serializePreparedMasterShowBinary(prepared))):undefined,[prepared]);
 const status=connection.status,connected=connection.phase==='Connected'||connection.phase==='Uploading'||connection.phase==='FirmwareUpdating',uploading=connection.phase==='Uploading',firmwareUpdating=connection.phase==='FirmwareUpdating';
 return <section className="page-content"><div className="section-heading"><div><p className="eyebrow violet">HARDWARE</p><h2>Device workspace</h2><p>Connect by serial or raw TCP. Bindings persist by stable device ID, never COM port or IP address.</p></div></div>{message&&<p className="notice">{message}</p>}<div className="device-grid">
  <Panel title="ESP32 connection" icon={<Cable size={17}/>}><div className="device-content"><div className="device-actions"><button className={connectionType==='serial'?'button primary':'button secondary'} disabled={connected} onClick={()=>setConnectionType('serial')}>Serial</button><button className={connectionType==='network'?'button primary':'button secondary'} disabled={connected} onClick={()=>setConnectionType('network')}>Network</button></div>{connectionType==='serial'?<div className="device-actions"><button className="button secondary" onClick={()=>void app.hardware.refreshPorts()}><RefreshCw size={13}/> Refresh Ports</button><select value={selectedPort} disabled={connected} onChange={e=>setSelectedPort(e.target.value)}><option value="">Select port…</option>{ports.map(p=><option key={p.portName} value={p.portName}>{p.portName} · {p.product??p.portType}</option>)}</select>{!connected&&<button className="button primary" disabled={!selectedPort||connection.phase==='Connecting'||connection.phase==='Handshaking'} onClick={()=>void app.hardware.connect({kind:'serial',portName:selectedPort})}>Connect</button>}</div>:<div className="device-actions"><label>Host / IP <input aria-label="Host / IP" value={host} disabled={connected} onChange={e=>setHost(e.target.value)}/></label><label>Port <input aria-label="TCP port" type="number" min="1" max="65535" value={port} disabled={connected} onChange={e=>setPort(Number(e.target.value))}/></label>{!connected&&<button className="button primary" disabled={!host.trim()||port<1||port>65535||connection.phase==='Connecting'||connection.phase==='Handshaking'} onClick={()=>void app.hardware.connect({kind:'tcp',host:host.trim(),port})}>Connect</button>}</div>}{connected&&<button className="button secondary" onClick={()=>void app.hardware.disconnect()}>Disconnect</button>}<dl className="device-data"><Row k="Connection" v={connection.phase}/><Row k="Endpoint" v={connection.endpoint??'—'}/><Row k="Device ID" v={connection.identity?.deviceId??'—'}/><Row k="Firmware" v={connection.identity?.firmwareVersion??'—'}/><Row k="Protocol" v={connection.identity?String(connection.identity.protocolVersion):'—'}/><Row k="Device state" v={status?DeviceState[status.deviceState]:'—'}/></dl>{connected&&<p className="notice">Disconnect does not send STOP; the device may continue running autonomously.</p>}</div></Panel>
  {connected&&<Panel title="Network settings" icon={<Cable size={17}/> }><div className="device-content">{connection.networkConfig?.recoveryMode&&<div className="notice"><strong>Recovery mode</strong><br/>Connected through ESP32 recovery access point. Configure Wi-Fi and restart the device.</div>}<button className="button secondary" disabled={firmwareUpdating} onClick={()=>void app.hardware.getNetworkConfig().then(()=>{const v=connection.networkConfig;if(v){setNetSsid(v.ssid);setNetPort(v.tcpPort);}setNetPassword('');setChangePassword(false);setMessage('');})}>Refresh settings</button><label>SSID <input aria-label="Network SSID" value={netSsid} disabled={firmwareUpdating} onChange={e=>setNetSsid(e.target.value)}/></label><label><input aria-label="Change password" type="checkbox" checked={changePassword} disabled={firmwareUpdating} onChange={e=>{setChangePassword(e.target.checked);setNetPassword('');}}/> Change password</label><label>Password <input aria-label="Network password" type="password" value={netPassword} disabled={!changePassword||firmwareUpdating} onChange={e=>setNetPassword(e.target.value)}/></label><small>{changePassword?'The entered value replaces the password; leave it blank to clear it for an open network.':'The existing password will be kept and is never displayed.'}</small><label>TCP port <input aria-label="Network TCP port" type="number" min="1" max="65535" value={netPort} disabled={firmwareUpdating} onChange={e=>setNetPort(Number(e.target.value))}/></label><Row k="Recovery mode" v={connection.networkConfig?.recoveryMode?'Yes':'No'}/><div className="device-actions"><button className="button secondary" disabled={!netSsid||netPort<1||netPort>65535||firmwareUpdating} onClick={()=>void app.hardware.setNetworkConfig({ssid:netSsid,password:changePassword?netPassword:undefined,tcpPort:netPort}).then(()=>setMessage('Settings saved.'))}>Apply</button><button className="button primary" disabled={!netSsid||netPort<1||netPort>65535||firmwareUpdating} onClick={()=>void app.hardware.setNetworkConfig({ssid:netSsid,password:changePassword?netPassword:undefined,tcpPort:netPort}).then(()=>app.hardware.reboot()).then(()=>setMessage('Settings saved. Device is restarting. Reconnect using the new network settings.'))}>Apply &amp; Restart</button></div></div></Panel>}
  {connected&&<Panel title="Firmware" icon={<Cpu size={17}/> }><div className="device-content"><p>Current firmware: <strong>{connection.identity?.firmwareVersion}</strong></p><label className="button secondary">Select firmware .bin<input hidden aria-label="Select firmware .bin" type="file" accept=".bin" onChange={e=>{const file=e.target.files?.[0];if(file)void file.arrayBuffer().then(buffer=>{const bytes=new Uint8Array(buffer);setFirmware({name:file.name,bytes,hash:hex(sha256(bytes))});});}}/></label>{firmware&&<dl className="device-data"><Row k="File" v={firmware.name}/><Row k="Size" v={`${firmware.bytes.length} bytes`}/><Row k="SHA-256" v={firmware.hash}/></dl>}<button className="button primary" disabled={!firmware||firmwareUpdating||uploading} onClick={()=>firmware&&void app.hardware.updateFirmware(firmware.bytes).then(()=>setMessage('Firmware staged successfully'))}>Update firmware</button>{firmwareUpdating&&<><progress value={connection.firmwareProgress?.sent??0} max={connection.firmwareProgress?.total??1}/><button className="button danger" onClick={()=>void app.hardware.cancelFirmwareUpdate()}>Cancel</button></>}{connection.firmwareStaged&&<><p className="notice">Firmware uploaded successfully. Restart the ESP32 to boot the new version.</p><button className="button primary" disabled={firmwareUpdating} onClick={()=>void app.hardware.reboot()}>Restart ESP32</button></>}</div></Panel>}
  <Panel title="Master binding" icon={<Cpu size={17}/>}><div className="device-content">{bound?<><p>Bound to: <strong>{bound.costume} / {bound.master.displayName}</strong></p><button className="button secondary" onClick={()=>app.hardware.unbind(bound.master.id)}>Unbind</button></>:<><select value={masterId} onChange={e=>setMasterId(e.target.value)}><option value="">Bind to Master…</option>{masters.map(m=><option key={m.master.id} value={m.master.id}>{m.costume} / {m.master.displayName}</option>)}</select><button className="button secondary" disabled={!connected||!masterId} onClick={()=>app.hardware.bind(masterId)}>Bind connected ESP32</button></>}</div></Panel>
  <Panel title="Device diagnostics" icon={<Activity size={17}/>}><div className="device-content"><div className="device-actions"><button className="button secondary" disabled={!connected||uploading||firmwareUpdating} onClick={()=>void app.hardware.refreshStatus()}>Refresh Status</button><button className="button primary" disabled={!connected||!bound||!prepared||uploading||firmwareUpdating||status?.deviceState===DeviceState.RUNNING} onClick={()=>void app.hardware.upload(bound!.master.id)}>Upload &amp; Activate</button>{uploading&&<button className="button danger" onClick={()=>void app.hardware.cancelUpload()}>Cancel Upload</button>}</div>{connection.uploadProgress&&<progress value={connection.uploadProgress.sent} max={connection.uploadProgress.total}/>}<dl className="device-data"><Row k="Pico feedback / configured" v={status?`Unavailable (one-way) / ${status.picoConfigured}`:'—'}/><Row k="Local artifact" v={short(localHash)}/><Row k="Device active" v={short(status?.activeArtifact)}/><Row k="Comparison" v={compareArtifacts(localHash,status?.activeArtifact)}/><Row k="Candidate" v={short(status?.candidateArtifact)}/><Row k="Duration / position" v={status?`${status.durationMs} / ${status.positionMs} ms`:'—'}/><Row k="Fault" v={status?`${status.fault} (${status.faultDetail})`:'—'}/><Row k="Late frames" v={status?String(status.lateFrames):'—'}/><Row k="Max lateness" v={status?`${status.maxLatenessUs} µs`:'—'}/></dl><div className="device-actions"><button className="button primary" disabled={!connected||uploading||firmwareUpdating||!status?.activeArtifact||status.fault!==0} onClick={()=>void app.hardware.start()}>Start Show</button><button className="button secondary" disabled={!connected||uploading||firmwareUpdating||!(status?.deviceState===DeviceState.RUNNING||status?.deviceState===DeviceState.READY)} onClick={()=>void app.hardware.stop()}>Stop Show</button></div></div></Panel>
 </div></section>;
}
function Row({k,v}:{k:string;v:string}){return <div><dt>{k}</dt><dd>{v}</dd></div>}
function Panel({title,icon,children}:{title:string;icon:ReactNode;children:ReactNode}){return <section className="panel"><h3>{icon}{title}</h3>{children}</section>}
