import { Activity, Cable, Cpu, RefreshCw } from 'lucide-react';
import { useMemo, useState, type ReactNode } from 'react';
import { DeviceState, hex } from '../../desktopEsp32/protocol';
import { compareArtifacts } from '../../desktopEsp32/connection';
import { serializePreparedMasterShowBinary } from '../../desktopEsp32/preparedBinary';
import { sha256 } from '../../desktopEsp32/sha256';
import { useAppState } from '../state/AppState';

const short=(value?:string)=>value?`${value.slice(0,12)}…`:'—';
export function DevicesPage() {
 const app=useAppState(),{connection,ports}=app.hardware,[selectedPort,setSelectedPort]=useState(''),[masterId,setMasterId]=useState('');
 const masters=app.project?.costumes.map(c=>({costume:c.name,master:c.master}))??[];
 const binding=app.project?.deviceBindings.find(b=>b.physicalDevice.type==='esp32'&&b.physicalDevice.hardwareId.toLowerCase()===connection.identity?.deviceId);
 const bound=masters.find(m=>m.master.id===binding?.logicalControllerId),prepared=app.preparation.result?.masters.find(m=>m.masterId===binding?.logicalControllerId);
 const localHash=useMemo(()=>prepared?hex(sha256(serializePreparedMasterShowBinary(prepared))):undefined,[prepared]);
 const status=connection.status,connected=connection.phase==='Connected'||connection.phase==='Uploading',uploading=connection.phase==='Uploading';
 return <section className="page-content"><div className="section-heading"><div><p className="eyebrow violet">HARDWARE</p><h2>Device workspace</h2><p>One wired ESP32 Master connection. Bindings persist by device ID, never COM port.</p></div></div><div className="device-grid">
  <Panel title="Serial connection" icon={<Cable size={17}/>}><div className="device-content"><div className="device-actions"><button className="button secondary" onClick={()=>void app.hardware.refreshPorts()}><RefreshCw size={13}/> Refresh Ports</button><select value={selectedPort} disabled={connected} onChange={e=>setSelectedPort(e.target.value)}><option value="">Select port…</option>{ports.map(p=><option key={p.portName} value={p.portName}>{p.portName} · {p.product??p.portType}</option>)}</select>{connected?<button className="button secondary" onClick={()=>void app.hardware.disconnect()}>Disconnect</button>:<button className="button primary" disabled={!selectedPort||connection.phase==='Connecting'||connection.phase==='Handshaking'} onClick={()=>void app.hardware.connect(selectedPort)}>Connect</button>}</div><dl className="device-data"><Row k="Connection" v={connection.phase}/><Row k="Port" v={connection.port??'—'}/><Row k="Device ID" v={connection.identity?.deviceId??'—'}/><Row k="Firmware" v={connection.identity?.firmwareVersion??'—'}/><Row k="Protocol" v={connection.identity?String(connection.identity.protocolVersion):'—'}/><Row k="Device state" v={status?DeviceState[status.deviceState]:'—'}/></dl>{connected&&<p className="notice">Disconnect does not send STOP; the device may continue running autonomously.</p>}</div></Panel>
  <Panel title="Master binding" icon={<Cpu size={17}/>}><div className="device-content">{bound?<><p>Bound to: <strong>{bound.costume} / {bound.master.displayName}</strong></p><button className="button secondary" onClick={()=>app.hardware.unbind(bound.master.id)}>Unbind</button></>:<><select value={masterId} onChange={e=>setMasterId(e.target.value)}><option value="">Bind to Master…</option>{masters.map(m=><option key={m.master.id} value={m.master.id}>{m.costume} / {m.master.displayName}</option>)}</select><button className="button secondary" disabled={!connected||!masterId} onClick={()=>app.hardware.bind(masterId)}>Bind connected ESP32</button></>}</div></Panel>
  <Panel title="Device diagnostics" icon={<Activity size={17}/>}><div className="device-content"><div className="device-actions"><button className="button secondary" disabled={!connected||uploading} onClick={()=>void app.hardware.refreshStatus()}>Refresh Status</button><button className="button primary" disabled={!connected||!bound||!prepared||uploading||status?.deviceState===DeviceState.RUNNING} onClick={()=>void app.hardware.upload(bound!.master.id)}>Upload &amp; Activate</button>{uploading&&<button className="button danger" onClick={()=>void app.hardware.cancelUpload()}>Cancel Upload</button>}</div>{connection.uploadProgress&&<progress value={connection.uploadProgress.sent} max={connection.uploadProgress.total}/>}<dl className="device-data"><Row k="Pico feedback / configured" v={status?`Unavailable (one-way) / ${status.picoConfigured}`:'—'}/><Row k="Local artifact" v={short(localHash)}/><Row k="Device active" v={short(status?.activeArtifact)}/><Row k="Comparison" v={compareArtifacts(localHash,status?.activeArtifact)}/><Row k="Candidate" v={short(status?.candidateArtifact)}/><Row k="Duration / position" v={status?`${status.durationMs} / ${status.positionMs} ms`:'—'}/><Row k="Fault" v={status?`${status.fault} (${status.faultDetail})`:'—'}/><Row k="Late frames" v={status?String(status.lateFrames):'—'}/><Row k="Max lateness" v={status?`${status.maxLatenessUs} µs`:'—'}/></dl><div className="device-actions"><button className="button primary" disabled={!connected||uploading||!status?.activeArtifact||status.fault!==0} onClick={()=>void app.hardware.start()}>Start Show</button><button className="button secondary" disabled={!connected||uploading||!(status?.deviceState===DeviceState.RUNNING||status?.deviceState===DeviceState.READY)} onClick={()=>void app.hardware.stop()}>Stop Show</button></div></div></Panel>
 </div></section>;
}
function Row({k,v}:{k:string;v:string}){return <div><dt>{k}</dt><dd>{v}</dd></div>}
function Panel({title,icon,children}:{title:string;icon:ReactNode;children:ReactNode}){return <section className="panel"><h3>{icon}{title}</h3>{children}</section>}
