import { useState, type FormEvent } from 'react';
import { FilePlus2, FolderOpen, History, Trash2 } from 'lucide-react';
import { useAppState } from '../state/AppState';
import { EmptyState } from '../components/EmptyState';

export function ProjectsPage() {
  const { createProject, openProject, recentProjects, openRecent, removeRecent } = useAppState(); const [creating, setCreating] = useState(false);
  return <section className="page-content projects-page"><div className="section-heading"><div><p className="eyebrow violet">LIGHT SHOW WORKSPACE</p><h2>Projects</h2><p>Create a show or open a local .lightshow project file.</p></div><div className="heading-actions"><button className="button secondary" onClick={() => void openProject()}><FolderOpen size={17}/> Open Project</button><button className="button primary" onClick={() => setCreating(true)}><FilePlus2 size={17}/> New Project</button></div></div>
    <h3 className="recent-heading"><History size={16}/> Recent Projects</h3>
    {recentProjects.length === 0 ? <EmptyState compact icon={<History size={26}/>} title="No recent projects" description="Projects you save or open will appear here."/> : <div className="project-list">{recentProjects.map(entry => <article className="project-card" key={entry.path}><div className="project-details"><h3>{entry.displayName}</h3><p className="project-path" title={entry.path}>{entry.path}</p><p>Opened {new Date(entry.lastOpenedAt).toLocaleString()}</p></div><div className="card-actions"><button className="icon-button danger-text" aria-label={`Remove ${entry.displayName} from recent`} onClick={() => void removeRecent(entry.path)}><Trash2 size={15}/></button><button className="button secondary" onClick={() => void openRecent(entry.path)}>Open</button></div></article>)}</div>}
    {creating && <ProjectNameDialog onCancel={() => setCreating(false)} onSubmit={async name => { await createProject(name); setCreating(false); }}/>}</section>;
}
function ProjectNameDialog({ onCancel, onSubmit }: { onCancel: () => void; onSubmit: (name: string) => Promise<void> }) { const [name, setName] = useState(''); const submit = (event: FormEvent) => { event.preventDefault(); if (name.trim()) void onSubmit(name); }; return <div className="dialog-backdrop"><form className="dialog" role="dialog" aria-modal="true" onSubmit={submit}><h2>New Project</h2><p>Create an unsaved project. You will choose its location on the first Save.</p><label htmlFor="project-name">Project name</label><input id="project-name" autoFocus value={name} onChange={event => setName(event.target.value)}/><div className="dialog-actions"><button type="button" className="button secondary" onClick={onCancel}>Cancel</button><button className="button primary" disabled={!name.trim()}>Create project</button></div></form></div>; }
