#include "pico_slave/command_processor.hpp"
#include "pico_slave/stream_parser.hpp"
#include <array>
#include <cstdio>
#include <cstdlib>
#include <vector>
using namespace pico_slave;
#define CHECK(x) do{if(!(x)){std::fprintf(stderr,"FAIL %d: %s\n",__LINE__,#x);std::exit(1);}}while(0)
class Outputs:public OutputController{public:bool initialize()override{states.fill(false);return true;}bool resetAll()override{states.fill(false);++resets;return true;}bool validateOutput(uint8_t x)const override{return x<4;}bool applyBatch(const OutputUpdate*u,size_t n)override{++applies;for(size_t i=0;i<n;i++)states[u[i].output_id]=u[i].on;return true;}size_t configuredCount()const override{return 4;}bool readState(uint8_t x,bool&o)const override{if(x>=4)return false;o=states[x];return true;}std::array<bool,4>states{};int resets{},applies{};};
Frame command(MessageType t,uint16_t seq,std::initializer_list<uint8_t>p={}){Frame f;f.message_type=uint8_t(t);f.slave_address=7;f.sequence=seq;f.session_id=0x89abcdef;f.payload_length=p.size();size_t i=0;for(auto x:p)f.payload[i++]=x;return f;}
std::vector<uint8_t> bytes(const Frame&f){std::array<uint8_t,kMaxFrameSize>b{};auto n=encodeFrame(f,b);return {b.begin(),b.begin()+n};}
void golden(const Frame&f,std::initializer_list<uint8_t>want){auto got=bytes(f);CHECK(got==std::vector<uint8_t>(want));Frame d;CHECK(decodeFrame(got.data(),got.size(),d));CHECK(d.sequence==f.sequence);}
int main(){CHECK(crc16CcittFalse((const uint8_t*)"123456789",9)==0x29b1);
 golden(command(MessageType::ResetOutputs,0x1234),{0xA5,0x5A,2,5,7,0x34,0x12,0xEF,0xCD,0xAB,0x89,0,0,0x15,0x14});
 golden(command(MessageType::SetOutputs,0x1235,{1,3,1}),{0xA5,0x5A,2,6,7,0x35,0x12,0xEF,0xCD,0xAB,0x89,3,0,1,3,1,0x59,0xE8});
 golden(command(MessageType::SetOutputs,0x1236,{3,1,1,2,0,3,1}),{0xA5,0x5A,2,6,7,0x36,0x12,0xEF,0xCD,0xAB,0x89,7,0,3,1,1,2,0,3,1,0x05,0xFD});
 Outputs o;o.states.fill(true);CommandProcessor cp(7,1,o);CHECK(cp.initialize());for(bool x:o.states)CHECK(!x);auto set=command(MessageType::SetOutputs,1,{2,0,1,2,1});cp.noteFrame();CHECK(cp.process(set)==CommandResult::SetApplied);CHECK(o.states[0]&&o.states[2]);auto applications=o.applies;cp.noteFrame();CHECK(cp.process(set)==CommandResult::Duplicate);CHECK(o.applies==applications);auto before=o.states;CHECK(cp.process(command(MessageType::SetOutputs,2,{2,0,0,0,1}))==CommandResult::Invalid);CHECK(o.states==before);CHECK(cp.process(command(MessageType::SetOutputs,3,{1,9,1}))==CommandResult::Invalid);CHECK(o.states==before);CHECK(cp.process(command(MessageType::SetOutputs,4,{1,0,2}))==CommandResult::Invalid);CHECK(o.states==before);std::vector<uint8_t>too(63);too[0]=31;auto over=command(MessageType::SetOutputs,5);over.payload_length=63;for(size_t i=0;i<63;i++)over.payload[i]=too[i];over.payload[0]=32;CHECK(cp.process(over)==CommandResult::Invalid);CHECK(cp.process(command(MessageType::ResetOutputs,6))==CommandResult::ResetApplied);for(bool x:o.states)CHECK(!x);
 StreamParser parser;Frame f;auto wire=bytes(set);for(size_t i=0;i+1<wire.size();i++)CHECK(parser.feed(wire[i],f)==StreamParser::Result::None);CHECK(parser.feed(wire.back(),f)==StreamParser::Result::FrameReady);auto bad=wire;bad.back()^=1;parser.reset();bool crc=false;for(auto x:bad)crc|=parser.feed(x,f)==StreamParser::Result::CrcError;CHECK(crc);auto old=wire;old[2]=1;auto oldCrc=crc16CcittFalse(old.data()+2,old.size()-4);old[old.size()-2]=uint8_t(oldCrc);old.back()=uint8_t(oldCrc>>8);parser.reset();bool invalid=false;for(auto x:old)invalid|=parser.feed(x,f)==StreamParser::Result::InvalidFrame;CHECK(invalid);parser.reset();for(auto x:{uint8_t(9),uint8_t(8),uint8_t(7)})parser.feed(x,f);bool recovered=false;for(auto x:wire)recovered|=parser.feed(x,f)==StreamParser::Result::FrameReady;CHECK(recovered);parser.reset();std::vector<uint8_t>oversized={0xA5,0x5A,2,6,7,0,0,0,0,0,0,65,0};for(auto x:oversized)invalid|=parser.feed(x,f)==StreamParser::Result::InvalidFrame;CHECK(invalid);
 cp.noteBytes(wire.size());cp.noteCrcError();cp.noteInvalidFrame();CHECK(cp.counters().bytesReceived==wire.size());CHECK(cp.counters().crcErrors==1&&cp.counters().invalidFrames>=1&&cp.counters().setCommandsApplied==1&&cp.counters().resetCommandsApplied==1);std::puts("All Pico v2 host tests passed");}
